In [1]:
#Si queremos que las imágenes sean mostradas en una ventana emergente quitar el inline
%matplotlib

# OpenCV-Python utiliza NumPy para el manejo de imágenes
import numpy as np
# cv2 es el módulo python para acceder a OpenCV 
import cv2 as cv
# Usamos las poderosas herramientas de graficación de matplotlib para mostrar imágenes, perfiles, histogramas, etc
import matplotlib.pyplot as plt


Using matplotlib backend: Qt5Agg


In [5]:
img_color = cv.imread('CoordCrom_1.png')

imgRGB = cv.cvtColor(img_color,cv.COLOR_BGR2RGB)

im_r,im_g,im_b = cv.split(imgRGB)
print(im_r)
print('Canal rojo')
plt.imshow(im_r,cmap = 'gray')
plt.show()
print('Canal verde')
plt.imshow(im_g,cmap = 'gray')
plt.show()
print('Canal azul')
plt.imshow(im_b,cmap = 'gray')
plt.show()

imgRGB2 = cv.merge((im_r,im_g*0,im_b*0))
plt.imshow(imgRGB2)
plt.show()


[[215 215 216 ... 209 206 207]
 [216 216 216 ... 204 207 205]
 [216 216 216 ... 205 206 204]
 ...
 [176 177 180 ... 149 152 151]
 [178 176 177 ... 152 155 152]
 [177 175 174 ... 156 152 151]]
Canal rojo
Canal verde
Canal azul
