In [18]:
#Si queremos que las imágenes sean mostradas en una ventana emergente quitar el inline
%matplotlib

# OpenCV-Python utiliza NumPy para el manejo de imágenes
import numpy as np
# cv2 es el módulo python para acceder a OpenCV 
import cv2 as cv
# Usamos las poderosas herramientas de graficación de matplotlib para mostrar imágenes, perfiles, histogramas, etc
import matplotlib.pyplot as plt


Using matplotlib backend: Qt5Agg


In [59]:
#IMAGEN 1
img_tito_1 = cv.imread('CoordCrom_1.png')
#print (img_tito_1.shape)
imgRGB1 = cv.cvtColor(img_tito_1,cv.COLOR_BGR2RGB)

im_r,im_g,im_b = cv.split(img_tito_1)
#print(im_r)
#print ("---------------------")
#print(im_g)
#print ("---------------------")
#print(im_b)

suma = im_r + im_g + im_b 
suma[suma==0] = 1
print (suma.shape)

im_r2 = im_r / suma
im_g2 = im_g / suma
im_b2 = im_b / suma
print(im_r2)

imgRGB2 = cv.merge((im_r2,im_g2,im_b2))
plt.imshow(imgRGB2)
plt.show()

#plt.imshow(im_b, interpolation='nearest') #para llevar de matriz a imagen
#plt.show()

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(996, 908)
[[1.66923077 1.6744186  1.65648855 ... 2.72727273 3.10526316 3.2       ]
 [1.6744186  1.6744186  1.6744186  ... 3.43137255 2.96666667 3.25925926]
 [1.66153846 1.64393939 1.64393939 ... 3.2        3.14285714 3.46      ]
 ...
 [0.66883117 0.65822785 0.64071856 ... 1.02702703 0.95180723 0.975     ]
 [0.65408805 0.66666667 0.66451613 ... 0.95180723 0.89130435 0.95180723]
 [0.65384615 0.66447368 0.66666667 ... 0.88172043 0.96296296 1.01333333]]


In [58]:
#IMAGEN 2
img_tito_2 = cv.imread('CoordCrom_2.png')
#print (img_tito_2.shape)
imgRGB1 = cv.cvtColor(img_tito_2,cv.COLOR_BGR2RGB)

im_r,im_g,im_b = cv.split(img_tito_2)

suma = im_r + im_g + im_b 
suma[suma==0] = 1
print (suma.shape)

im_r2 = im_r / suma
im_g2 = im_g / suma
im_b2 = im_b / suma
print(im_r2)

imgRGB2 = cv.merge((im_r2,im_g2,im_b2))
plt.imshow(imgRGB2)
plt.show()


Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(996, 908)
[[ 1.22093023  1.25301205  1.4084507  ... 71.          0.27559055
   0.27559055]
 [ 1.2875      1.36486486  1.36486486 ...  0.27559055  0.27346939
   0.27346939]
 [ 1.36486486  1.32467532  1.4084507  ...  0.27559055 18.
   0.27419355]
 ...
 [ 0.14876033  0.15322581  0.14166667 ...  0.13592233  0.1122449
   0.125     ]
 [ 0.15748031  0.1440678   0.15079365 ...  0.13592233  0.12121212
   0.11881188]
 [ 0.14876033  0.16541353  0.15503876 ...  0.11702128  0.13
   0.12371134]]


In [60]:
#IMAGEN 3
img_tito_3 = cv.imread('CoordCrom_3.png')
#print (img_tito_3.shape)
imgRGB1 = cv.cvtColor(img_tito_3,cv.COLOR_BGR2RGB)

im_r,im_g,im_b = cv.split(img_tito_3)

suma = im_r + im_g + im_b 
suma[suma==0] = 1
print (suma.shape)

im_r2 = im_r / suma
im_g2 = im_g / suma
im_b2 = im_b / suma
print(im_r2)

imgRGB2 = cv.merge((im_r2,im_g2,im_b2))
plt.imshow(imgRGB2)
plt.show()


Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(996, 908)
[[0.28415301 0.28921569 0.28787879 ... 0.33557047 0.33557047 0.33552632]
 [0.28921569 0.28645833 0.28921569 ... 0.33557047 0.33557047 0.33566434]
 [0.29064039 0.29126214 0.28855721 ... 0.33557047 0.33566434 0.33557047]
 ...
 [0.11111111 0.12       0.11111111 ... 0.02439024 0.06521739 0.09615385]
 [0.12987013 0.12820513 0.12820513 ... 0.08       0.10714286 0.08      ]
 [0.12820513 0.12       0.13580247 ... 0.08       0.08       0.08      ]]
